### ISSUE TITLE
Response Details Component

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#1]
Create a Component which can be used this way:

```
<ApiInterface endpoint="http://example.com/resourxe/ef7d-xj36p" method="GET" />
```

![image](https://user-images.githubusercontent.com/1054674/63231314-af4d1900-c1ce-11e9-99ca-f8be11a3f446.png)

![image](https://user-images.githubusercontent.com/1054674/63231324-e7545c00-c1ce-11e9-8013-346dceda64ff.png)

![image](https://user-images.githubusercontent.com/1054674/63231333-fe934980-c1ce-11e9-9644-dceffb0b0c1b.png)

It should also include:

* `status_code` returned by the endpoint as a color indicator.  Green=200, Yellow=300, Red=400, Black=500
* A string reporting the time in milliseconds consumed by the API call. 
* A div to display the output in `<pre>` tags.
* timeout input, 3 seconds default
* Radio button for [GET] [POST] [PUT] [DELETE]
* Button to send request

**Comment by katiarabelo** [comment]
Waiting direction about synchronization, according to message in Slack.

**Comment by kylepolich** [comment]
This can be closed.  I asked for next steps already in #fast-spa in slack.
