### ISSUE TITLE
Implement a Flask app

### ISSUE THREAD

**Issue by katiarabelo** [data-skeptic/fast-spa#10]
Implement a very simple Flask app in the fast-spa project which gives a simple demonstration of how to use FastSPA as a nice client-side user interface to a Flask API.  The API should have one GET and one POST endpoint and also provide a Swagger file.  On the FastSPA side, it needs to have a “shell” HTML file (shell since <body><div id="fast_spa_container" /></body>)

**Comment by areeves87** [comment]
Collect the bundle and the html file for the flask app. Probably from other Alex but maybe from Cory.

**Comment by areeves87** [comment]
Alex, please add a new endpoint which returns df.to_json() which is Pandas unique JSON format for a table.  We want FastSPA to recognize it and make a beautiful Table layout, so it would be good to provide an example of the format to Alperen

Also, give an endpoint which require pagination in the for of /get_integers?limit=3&offset=2 which returns [{"value": 2},{"value": 3},{"value": 4}]

**Comment by areeves87** [comment]
Kyle has these notes for a json viewer/editor page in fast-spa app
```
Page 6:
• Has two side by side JSON Viewers with a JSON dictionary provided by the API
• The user can edit the JSON format
• The user has a `[SAVE]` button which will POST their changes to the API in a request-body

Maybe a component like this:

<JsonViewer editable="true" src="http://.../blah" onSavePostResultTo="http://.../blah" />
```

**Comment by katiarabelo** [comment]
➤ Alex Reeves commented:

Waiting for alperen deliverable
