### ISSUE TITLE
S3 Explorer Variant

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#106]
- [x] Create a new "Portal Application" only accessible to kyle@ and cory@ name "ID Images"

- [x] Create a new file `serverless-crawl` named `user/test/apps/idimages/.feaas` which contains:
```
APP=idimages
```
- [x] If the user navigates in Forager to folder with `.feaas`, open it and check if `APP` is `idimages`.  If so, show THIS component.  If not, show default Forager

Extend the existing S3Explorer / Forager class with a child component that is specialized to the ID Images project.

- [x] This variant shows ONLY directories and `*.pdf` files.  Nothing else, nothing more.

- [x] For directories use font-awesome and/or CSS to make the Component more distinctively a "folder".

- [x] For `*.pdf` files, hide the file extension.

- [x] Base directory for this FastSPA app is `user/test/apps/idimages/labels/`.  For anyone with access to this app, when they open it, that's the default directory, and they cannot navigate further up.  It's root.

- [x] Uploads are placed in `inbox/yyyy/mm/dd/filename.pdf` use the filename that the uploader provides.

- [ ] If a duplicate filename is going to be uploaded, make Uppy prevent it.  At a minimum, give an error and force them to local rename.  If Uppy has *out of box* features that are more elegant, you can use those.  For something more helpful (like auto-renaming), that will be a later project.

- [x] Only accept PDFs when uploading in this Component

- [ ] After upload complete, take the user to the appropriate directory and auto-scroll-to/select the new file

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

The only sub-tasks left on this are the ones relating to the user uploading, and root directory - this involves another task that needs to be created to fix an issue with current directory structure and how it's being parsed.
