### ISSUE TITLE
Members Portal Application

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#141]
- [ ] If Portal user is a DS Member, put a shortcut on their home page and menu (#139)
- [ ] When clicking the shortcut, take the user to `user/dataskeptic/members/bucket/` (notice this unusual name username!  On purpose!).
- [ ] This directory will contain `.feaas` with `APP=data_skeptic_members`
- [ ] `data_skeptic_members` is Bucket Blog with some custom styles
- [ ] Route the subdomain members.dataskeptic.com to redirect to either `/login` or the user's root members page

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

Requires #196 to be done since this is basically a "custom app".
