### ISSUE TITLE
Shopping cart

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#149]
DO NOT RE-INVENT THE WHEEL.

**Find an off the shelf solution we can repurpose**

- [ ] One department in the store
- [ ] List of products is stored in Printful
- [ ] Product can be added to Cart
- [ ] Cart side menu / tray
- [ ] Checkout flow - billing, shipping, CC, etc. (should model #147)
- [ ] Submit order via Stripe
- [ ] Submit order via FEaaS to Printful
- [ ] Clear cart on successful checkout
- [ ] Publish successful checkout message

**Comment by kylepolich** [comment]
Use: 

https://github.com/jeffersonRibeiro/react-shopping-cart

https://codesandbox.io/s/74rykw70qq

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

@Kyle Polich ( https://app.asana.com/0/1120730780628911/list )
After looking in the link that you shared on GitHub, https://github.com/jeffersonRibeiro/react-shopping-cart, I have realized that this is not a component, nor is it a set of components. This is a full pre-built app/site that is designed to run on its own.

This being said, it will not be usable, at least not in the way that we need it to be.
