### ISSUE TITLE
S3Explorer

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#22]
Extend / refactor #5.

```
<S3Explorer prefix="user/test/" upload_folder="user/test/inbox/" />
```

* Re-uses the Component from DCS for "Image Library"
* If the user clicks a file (not a folder), open a "File Details" sidebar pane and display all the metadata of the S3 object
* Right click on a File opens a menu with these options:
    * delete
    * download
    * edit
* Ensure Right click implementation is extensible for future efforts such as #68
* By default, "edit" goes to TextEditor #37
* For common image formats, use ImageEditor #35 
* Use #3 for .csv, .tsv
* Use #39 for .mp3 and .wav
* Use #40 for any supported videos
* Use #2 for .json
* Use #47 for .html and .crawl

**Comment by katiarabelo** [comment]
@Heartless49, please add comments if you have any.

**Comment by kylepolich** [comment]
IMPORTANT NOTE:

As work begins on this ticket.  It is 100% unacceptable to build new Components to replace those already built in #37, #35, #38, #39, #40, #2 

As such, this is a fairly straightforward ticket

If there is *ANY REASON* why this cannot be completed in 4-8 hours, IMMEDIATELY call Kyle at 312-719-0752 to discuss.
