### ISSUE TITLE
Elastic Search

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#238]
* [x] Free users do not get this option
* [x] Paid or @dataskeptic.com users get these options
* [x] Each Portal App has a property indicating whether or not it wants to store things in elastic search.  It should be `true` for only Forager right now.
* [x]  Free user sees search box on their dashboard only.  Clicking it gives modal saying "Search is a paid feature.  Please consider upgrading"
* [ ] If the user is "in" the an app, show a serach box conditioned on the field
* [x] If the user has access to search, it appears on their Dashboard
* [ ] Search on the Dashboard searches ALL files which are WITHIN `/user/{username}/`
* [ ] If the user is in the app and searches, search WITHIN `/user/{username}/apps/{app_name}/`
* [x] Display nice search results on a page (not a modal)
* [x] Search results include a button to copy the results (as JSON) to the clipboard
* [ ] Search results include a button to `[Save]` the results to `user/{username}/search/results/{yyyymmdd}/search_result_{timestamp}.json

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

Going to need some credentials or something for this; the ones that I have been using are now giving me a security exception:

`unable to authenticate user [elastic] for REST request [/feaas/_search]`

The only thing that I have is the elastic search endpoint, which i was instructed to get from dataskeptic.com originally; not sure if this is the correct one for this project anymore.
