### ISSUE TITLE
portal.dataskeptic.com/signup

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#239]
Make this endpoint `/signup` which is a sign up form for creating an account.  If the user visits `/signup` then they are FORCED to purchase a $12 account.  Their account has:

- [x] Forager
- [x] Elastic  search option

- [x] Ask @vanessably to make the Stripe $12 account for you

**Comment by vanessably** [comment]
@Heartless49  I created the $12 plan on stripe. Not sure if you need anything from me but.... 

Portal Subscription
plan_GkfcbUx91XHZS5 |  
prod_Gkfb9bF6c0LZuv
