### ISSUE TITLE
TabViewer

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#24]
```
<TabViewer bucket="b" prefix="user/test/uploads/filename_*" postfixes=["*.jpg", "*.jpeg", "*.mov", "*.pdf"] />
```

Make it like the functionality in ID Images.  Get all files that start with `prefix` and end in `postfixes`.  However, instead of Tabs at the top, make it in the same way we have DCS menu:

![image](https://user-images.githubusercontent.com/1054674/69932135-bf87bc00-147e-11ea-85d5-636b28d8145b.png)

The title for the Tab should only be the filename, not the leading folder names and slashes.

**Comment by kylepolich** [comment]
@alperendev98 please be sure to maximize code re-use with http://recordit.co/OT43d4dWNg.  @Heartless49 please comment if you have anything to add.

**Comment by Heartless49** [comment]
@kylepolich 
This functionality already exists in `bucket-blog`.
