### ISSUE TITLE
Not redirecting after upload

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#284]
http://recordit.co/L7ka7BM027

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1164506337246060">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1164506337246062">image.png</a>

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

not a bug. uploads do not upload to the folder you are in, they upload to your user uploads directory according to the the original upload ticket.

**Comment by kylepolich** [comment]
@Heartless49 Can you point to what you are referring to?  It should definitely be uploading to that directory or at least redirecting to their after upload complete.
