### ISSUE TITLE
WysiwygEditor

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#36]
Find a simple off-the-shelf npm library which gives you a standard WYSIWYG Component which can edit/create/save markdown files.

Usage is described in #22

Please be sure to review the work of @brave-merida seen here: https://github.com/kylepolich/dialog-creation-system/pull/2448

**Comment by brave-merida** [comment]
I've updated the Wysiwyg editor in https://github.com/kylepolich/dialog-creation-system/pull/2544
