### ISSUE TITLE
Loading swagger file

### ISSUE THREAD

**Issue by katiarabelo** [data-skeptic/fast-spa#4]

**Comment by katiarabelo** [comment]
From Alperen:
My concern is loading body parameters.
http://prntscr.com/p1yz77
I think that I need to load swagger’s body example and show it to fast-spa
https://screenpresso.com/=g3U5e

btw, I'm confused about this task(
c0deslave49 11:14 PM
Swagger?
11:14 PM
None of the APIs that we make or use ever have anything related to swagger, or yaml files... (edited) 
11:15 PM
Confused about what you're making that would require this...
)

**Comment by kylepolich** [comment]
@Heartless49 Swagger is a format that many systems can save to/from.  For example, API gateway, like Claudia.js apps

**Comment by katiarabelo** [comment]
➤ alperenaksoydev commented:

My concern is loading body parameters.
http://prntscr.com/p1yz77
I think that I need to load swagger’s body example and show it to fast-spa
https://screenpresso.com/=g3U5e

btw, I'm confused about this task(
c0deslave49 11:14 PM
Swagger?
11:14 PM
None of the APIs that we make or use ever have anything related to swagger, or yaml files... (edited) 
11:15 PM
Confused about what you're making that would require this...
)
