### ISSUE TITLE
50 years ago?

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#501]
![image](https://user-images.githubusercontent.com/1054674/78419108-13560d80-75f7-11ea-8d42-1e2085044de2.png)

**Comment by Heartless49** [comment]
This is odd, but it's getting that data from elastic search and using `moment.js` to format it. The actual timestamps that it's getting seem to be wrong. I had it log the timestamps that it gets from the query, next to the standard date object that it gets from that in the screenshot below.

That's the only data that I have - we can either find the issue within elastic search, or whatever is creating that data, or I can remove the date reference from the front-end.

![image](https://user-images.githubusercontent.com/1939701/78586837-e8cfa480-77f0-11ea-9957-49cb5973683f.png)

**Comment by kylepolich** [comment]
@Heartless49 the values are in miliseconds.  If you need seconds, divide by 1000
