### ISSUE TITLE
Prefix page not appearing

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#593]
https://portal.dataskeptic.com/app/e4a3491e-fcf5-499e-858e-fd535b3901cc/inbox/3108682167/dt=2020-03-31-19/

http://recordit.co/KnD46yU0rS

**Comment by Heartless49** [comment]
@kylepolich 
This is loading just fine - you have permissions set on that directory to not allow write access which hides the configurations, and actions, and there is no readme, so there is nothing to display.

Maybe we should have a "You do not have access to this directory." type of message for this situation?

**Comment by kylepolich** [comment]
Ahhh, good point.  Yeah, let's put up a message:

> Please make a selection on the left
