### ISSUE TITLE
Uppy integration

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#6]
In DCS, we have a nice integration using Uppy.  Let's find a convenient way to make it available in FastSPA also.

![image](https://user-images.githubusercontent.com/1054674/71328149-28cf7d80-24c7-11ea-941e-7d9d6c478c07.png)

Revise this space.  Convert the word "Back" to a Font Awesome back arrow.  Add another FA icon for uploading which brings up the Uppy Modal.  The file should be sent to the endpoint described in https://github.com/data-skeptic/serverless-upload-accepter, which is deployed here:

https://4buo70od4m.execute-api.us-east-2.amazonaws.com/prod/upload

**Comment by kylepolich** [comment]
@Heartless49 as with #5, please add any comments you have and then @alperendev98 can begin.

**Comment by alperendev98** [comment]
I implemented basic Uppy component via storybook.
I'm not sure what exactly needs to implement

**Comment by kylepolich** [comment]
@areeves87 Please add a Flask endpoint to your sample API which accepts a file to be uploaded and stores the file in S3 (surely boilerplate code that you can re-use in 30 minutes exists).  There are some tricky thing related to the `Content-Type` header.  You have to be in like `application/form:encypted` or something like that.  Check with @Heartless49 if you need help with that part.

The new endpoint should return a simple JSON.

On the FastSPA side of things, your custom Component should accept Alex's endpoint as it's parameter and provide a nice upload option and report back the success.

@Heartless49 any thoughts you have an implementation, please share ^

**Comment by areeves87** [comment]
@kylepolich how should I handle aws key, aws secret, S3 bucketname? Make them query strings? Or have them load from a local config/env file?

**Comment by kylepolich** [comment]
@Heartless49 Let's talk next work time about FEaaS's new `/upload` route

**Comment by Heartless49** [comment]
@kylepolich currently the endpoint provided results in a 403 error; i can only assume that this is because it's coming from the front-end, but for this specific use-case, it might need to unless we want to proxy it through another backend api on fast-spa, in which case this proxy api would need to be written.

**Comment by katiarabelo** [comment]
➤ Cory Armstrong commented:

As long as it's in storybook and works there, then it's good. I will take a look at the story tomorrow and let you know if anything else needs to be done.
