### ISSUE TITLE
Extend Right Click options

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/fast-spa#68]
Query the FEaaS API with a the `key` that was right clicked:

```
https://4buo70od4m.execute-api.us-east-2.amazonaws.com/prod/user/test/apps/utilities/api/transformation?key=user/test/apps/adf.crawl
```

The returned result will look like this:
```
[
  {
    "app": "webcrawler",
    "result": "Crawl2Text"
  }, {
    "app": "webcrawler",
    "result": "Crawl2Links"
  }
]
```

For now, *ignore* `app`, but display each value of `result` as a new value for the drop down menu.

As far as this ticket is concerned, the new options are not clickable yet.  That funcitonality will be defined in #69

**Comment by Heartless49** [comment]
I've got the visual portion of the right-click context menu ready, but trying to plugin this FEaaS thing doesn't  return anything for any file type at the moment.
